module

public import ECSBM.Theorem1

/-!
# Theorem 2: the clusters of the synthetic network keep their edge connectivity

Section "Theoretical guarantees" of the paper. EC-SBM was designed so that each cluster of the
synthetic network has edge connectivity at least the value desired for it, the minimum cut size of
the cluster in the empirical network. Theorem 2 proves this guarantee for the network that EC-SBM
returns, whatever `k`-edge-connected graph Step 1 starts from in each cluster. A run of EC-SBM is
an `ECSBM.Run`.

The proof follows the paper's. By Theorem 1, after Step 1 every non-singleton cluster has minimum
cut size at least its desired edge connectivity. The later steps only add edges, or remove excess
edges (self-loops and copies of parallel edges), which never removes an edge already present. So
the network after each step contains the result `N₀` of Step 1, and adding edges does not decrease
the minimum cut size of a cluster (`ECSBM.minCutSize_mono`).
-/

@[expose] public section

namespace ECSBM

open SimpleGraph

/-- Adding the edges of a multigraph to a graph and then removing the excess edges removes no edge
of the graph: the excess edges are self-loops, which a simple graph has none of, and the copies of
parallel edges beyond the one kept. -/
theorem le_addThenSimplify {W : Type*} (H : SimpleGraph W) (M : Multiset (Sym2 W)) :
    H ≤ addThenSimplify H M :=
  fun _ _ h => (fromEdgeSet_adj _).mpr ⟨Or.inl h, h.ne⟩

namespace Run

variable {W : Type*} [Fintype W] [DecidableEq W] {G : SimpleGraph W}
  {𝒞 : Finpartition (Finset.univ : Finset W)} (r : Run G 𝒞)

/-- "Step 2a adds edges, which cannot reduce the edge-connectivity of any cluster. Step 2b then
removes excess edges, but by definition, this cannot remove any edges present in `N₀`": the
network `N₁` at the end of Stage 1 contains `N₀`. -/
theorem step1Output_le_stage1Output : r.step1Output ≤ r.stage1Output :=
  le_addThenSimplify _ _

/-- Stage 2 adds the synthetic outlier subnetwork and removes excess edges, which "cannot remove
any edge in `N₁`". -/
theorem stage1Output_le_stage2Output : r.stage1Output ≤ r.stage2Output :=
  le_addThenSimplify _ _

/-- Stage 3 adds edges to improve the fit to the degree sequence, which "cannot remove any edge in
`N₁`". -/
theorem stage2Output_le_output : r.stage2Output ≤ r.output :=
  le_sup_left

/-- The cluster `C` in `N₀`, the result of Step 1, contains the spanning subnetwork that Step 1
generates for `C`. -/
theorem step1_output_le_induce {C : Finset W} (hC : C ∈ nonsingletonClusters 𝒞) :
    (r.step1 C hC).output ≤ r.step1Output.induce (C : Set W) :=
  calc (r.step1 C hC).output
      = ((r.step1 C hC).output.map (Function.Embedding.subtype _)).comap
          (Function.Embedding.subtype _) := (comap_map_eq _ _).symm
    _ ≤ r.step1Output.induce (C : Set W) :=
      comap_monotone _ (le_iSup₂_of_le C hC le_rfl)

end Run

/-- **Theorem 2** (`FPar3`). Let `G` be the clustered empirical network from which we derive
parameters for EC-SBM, and let `𝒞` denote its clustering. For a given cluster `C ∈ 𝒞`, let `N(C)`
denote the corresponding cluster in the synthetic network `N` generated by EC-SBM, allowing for
any way of initializing Step 1 of Stage 1. Then, for all clusters `C`, the size of the minimum
edge cut for `N(C)` in `N` is at least the size of the minimum edge cut for `C` in `G`.

The initializations of Step 1 are those of Theorem 1: in each non-singleton cluster `C`, Step 1
starts from a graph that is `k`-edge-connected, `k` being the desired edge connectivity of `C`
(the hypothesis `hinit`). For a singleton cluster both sides are `⊤`: a graph with one vertex has
no edge cut. -/
theorem theorem2 {W : Type*} [Fintype W] [DecidableEq W] (G : SimpleGraph W)
    (𝒞 : Finpartition (Finset.univ : Finset W)) (r : Run G 𝒞)
    (hinit : ∀ C (hC : C ∈ nonsingletonClusters 𝒞),
      (r.step1 C hC).N₀.IsEdgeConnected (desiredConnectivity G C)) :
    ∀ C ∈ 𝒞.parts,
      minCutSize (G.induce (C : Set W)) ≤ minCutSize (r.output.induce (C : Set W)) := by
  intro C hC
  by_cases hns : 1 < C.card
  · have hCn : C ∈ nonsingletonClusters 𝒞 := Finset.mem_filter.mpr ⟨hC, hns⟩
    obtain ⟨a, ha, b, hb, hab⟩ := Finset.one_lt_card.mp hns
    have : Nontrivial (C : Set W) := ⟨⟨⟨a, ha⟩, ⟨b, hb⟩, fun h => hab (congrArg Subtype.val h)⟩⟩
    have hk : minCutSize (G.induce (C : Set W)) = desiredConnectivity G C :=
      (ENat.natCast_toNat (minCutSize_lt_top _).ne).symm
    -- by Theorem 1, the minimum cut size of `C` in `N₀` is at least that of `C` in `G`
    have h₀ : minCutSize (G.induce (C : Set W)) ≤
        minCutSize (r.step1Output.induce (C : Set W)) := by
      rw [hk, le_minCutSize_iff]
      exact IsEdgeConnected.mono (theorem1 (r.step1 C hCn) (hinit C hCn)).2
        (r.step1_output_le_induce hCn)
    -- the later steps never remove an edge of `N₀`
    have hle : r.step1Output ≤ r.output :=
      r.step1Output_le_stage1Output.trans
        (r.stage1Output_le_stage2Output.trans r.stage2Output_le_output)
    exact h₀.trans (minCutSize_mono (comap_monotone _ hle))
  · -- a singleton cluster has no edge cut
    have : Subsingleton (C : Set W) :=
      ⟨fun x y => Subtype.ext (Finset.card_le_one.mp (not_lt.mp hns) x x.2 y y.2)⟩
    rw [minCutSize_eq_top (r.output.induce (C : Set W))]
    exact le_top

end ECSBM
