module

public import ECSBM.Theorem1

/-!
# Theorem 2: the clusters of the synthetic network keep their edge connectivity

Section "Theoretical guarantees" of the paper. EC-SBM was designed so that each cluster of the
synthetic network has edge connectivity at least the value desired for it, the minimum cut size of
the cluster in the empirical network. Theorem 2 proves this guarantee for the network that EC-SBM
returns, whatever `k`-edge-connected graph Step 1 starts from in each cluster. A run of EC-SBM is
an `ECSBM.Run`.

The proof follows the paper's. By Theorem 1, after Step 1 every non-singleton cluster has minimum
cut size at least its desired edge connectivity. The later steps only add edges, or remove excess
edges (self-loops and copies of parallel edges), which never removes an edge already present. So
the network after each step contains the result `N₀` of Step 1, and adding edges does not decrease
the minimum cut size of a cluster (`ECSBM.minCutSize_mono`).
-/

@[expose] public section

namespace ECSBM

open SimpleGraph

/-- **Theorem 2** (`FPar3`). Let `G` be the clustered empirical network from which we derive
parameters for EC-SBM, and let `𝒞` denote its clustering. For a given cluster `C ∈ 𝒞`, let `N(C)`
denote the corresponding cluster in the synthetic network `N` generated by EC-SBM, allowing for
any way of initializing Step 1 of Stage 1. Then, for all clusters `C`, the size of the minimum
edge cut for `N(C)` in `N` is at least the size of the minimum edge cut for `C` in `G`.

The initializations of Step 1 are those of Theorem 1: in each non-singleton cluster `C`, Step 1
starts from a graph that is `k`-edge-connected, `k` being the desired edge connectivity of `C`
(the hypothesis `hinit`). For a singleton cluster both sides are `⊤`: a graph with one vertex has
no edge cut. -/
theorem theorem2 {W : Type*} [Fintype W] [DecidableEq W] (G : SimpleGraph W)
    (𝒞 : Finpartition (Finset.univ : Finset W)) (r : Run G 𝒞)
    (hinit : ∀ C (hC : C ∈ nonsingletonClusters 𝒞),
      (r.step1 C hC).N₀.IsEdgeConnected (desiredConnectivity G C)) :
    ∀ C ∈ 𝒞.parts,
      minCutSize (G.induce (C : Set W)) ≤ minCutSize (r.output.induce (C : Set W)) := by
  sorry

end ECSBM
