module

public import Mathlib.Combinatorics.SimpleGraph.Connectivity.EdgeConnectivity
public import Mathlib.Combinatorics.SimpleGraph.Maps
public import Mathlib.Data.ENat.Lattice
public import Mathlib.Order.Partition.Finpartition

/-!
# EC-SBM synthetic network generator: the statements of record

The-Anh Vu-Le, Lahari Anne, George Chacko and Tandy Warnow, *EC-SBM synthetic network generator*,
Applied Network Science 10, 15 (2025), https://doi.org/10.1007/s41109-025-00701-2.

EC-SBM takes a clustered network `(G, 𝒞)` and generates a synthetic network on the same vertices,
with the same clustering. Its Stage 1, Step 1 builds, for each cluster `C` with at least two
vertices, a spanning subnetwork on `C` whose minimum cut size is at least that of `C` in `G`. The
later stages add edges generated by a stochastic block model (SBM), remove the self-loops and all
but one edge of each set of parallel edges, and add edges to fit the degree sequence. The paper
proves two guarantees.

**Theorem 1** (`ECSBM.Challenge.theorem1`). Start from any `k`-edge-connected graph `N₀` on a set
`V₀` of vertices of a cluster `V`, and add the other vertices of `V` one at a time, each made
adjacent to exactly `k` vertices already present. The resulting graph on `V` is
`k`-edge-connected.

**Theorem 2** (`ECSBM.Challenge.theorem2`). In the network that EC-SBM returns, the minimum cut
size of every cluster is at least its minimum cut size in the empirical network, whatever
`k`-edge-connected graphs Step 1 starts from.

## Conventions

* A network is a simple graph, `SimpleGraph W`. A multigraph is the multiset of its edges, an
  unordered pair `s(v, v)` being a self-loop and a repeated pair a parallel edge.
* A clustering is a partition of all the vertices, `Finpartition (Finset.univ : Finset W)`. The
  vertices of its singleton clusters are the outliers, as in the paper's sections "Terminology"
  and "Stochastic block model (SBM)" ("We consider all outliers to define singleton clusters").
  Section "Materials and methods" instead lets the outliers belong to no cluster; the two
  conventions differ only by the singleton clusters, for which Theorem 2 holds trivially (both of
  its sides are `⊤`).
* An edge cut of a graph is a set of its edges whose removal leaves a graph that is not
  preconnected, that is, splits it into at least two parts (`ECSBM.IsEdgeCut`). The minimum cut
  size `ECSBM.minCutSize` is the least number of edges of an edge cut, in `ℕ∞`, and `⊤` for a
  graph with at most one vertex, which has no edge cut. The minimum cut size of a cluster `C` of
  `G` is that of the induced subgraph `G.induce C`.
* A graph is `k`-edge-connected when its minimum cut size is at least `k`. This is Mathlib's
  `SimpleGraph.IsEdgeConnected k`: removing fewer than `k` edges leaves every two vertices joined
  by a path (`ECSBM.Challenge.le_minCutSize_iff`).
* `ECSBM.Step1Run V k` is a run of Step 1 on a cluster with vertex type `V` and desired edge
  connectivity `k`, started from a graph `N₀` on `V₀ ⊆ V`. The vertices outside `V₀` are added in
  the order `order 0, order 1, …` (indexed from `0`, where the paper writes `v₁, …, v_p`), and
  `order j` is made adjacent to the `k` vertices of `nbrs j`, each already present. The order and
  the neighbours are arbitrary; the paper chooses them by "availability", which is one choice.
  Each added vertex gets exactly `k` neighbours, as the paper's section "Theoretical guarantees"
  says; its Stage 1 description gives `min{k, |N₀|}` neighbours (printed `max{k, |N₀|}`, a
  misprint), which is the same once `k` vertices are present.
* `ECSBM.Run G 𝒞` is a run of EC-SBM: a run of Step 1 on every non-singleton cluster, with the
  desired edge connectivity of that cluster (its minimum cut size in `G`), the multigraphs that SBM
  generates in Stage 1 (Step 2a) and Stage 2, and the edges that Stage 3 adds. These three are
  arbitrary, so the model covers every run of EC-SBM. `ECSBM.addThenSimplify` adds a multigraph
  to a graph and removes the excess edges (the self-loops, and all but one edge of each set of
  parallel edges).
* Theorem 2 lets Step 1 start, in each non-singleton cluster, from any `k`-edge-connected graph,
  `k` being the desired edge connectivity of the cluster: these are the initializations of
  Theorem 1, which the paper's phrase "allowing for any way of initializing Step 1" refers to. The
  paper starts from a `(k + 1)`-clique, and `ECSBM.Challenge.Run.exists_clique` shows that such a
  run of EC-SBM exists for every clustered network.
* `ECSBM.Challenge.minCutSize_eq_zero_iff` and `ECSBM.Challenge.minCutSize_completeGraph` check
  that `ECSBM.minCutSize` has its usual meaning: it is `0` exactly for the graphs that are not
  preconnected (that have at least two connected components), and `n + 1` for the complete graph
  on `n + 2` vertices.
-/

@[expose] public section

-- BEGIN SHARED DEFINITIONS
namespace ECSBM

open SimpleGraph

/-! ### Edge cuts and the minimum cut size (Section "Terminology") -/

/-- An **edge cut** of a graph `H` (Section "Terminology"): a set `F` of edges of `H` whose
removal, keeping the endpoints, disconnects `H` into two or more parts. -/
def IsEdgeCut {V : Type*} (H : SimpleGraph V) (F : Set (Sym2 V)) : Prop :=
  F ⊆ H.edgeSet ∧ ¬ (H.deleteEdges F).Preconnected

/-- The **minimum cut size** of a graph `H` (Section "Terminology"): the size of a minimum edge
cut of `H`, or `⊤` when `H` has no edge cut, that is, when `H` has at most one vertex. The minimum
cut size of a cluster is that of the subgraph that its vertices induce. A graph is
`k`-edge-connected when its minimum cut size is at least `k`; the theorem `le_minCutSize_iff`
shows that this is Mathlib's `SimpleGraph.IsEdgeConnected`. -/
noncomputable def minCutSize {V : Type*} (H : SimpleGraph V) : ℕ∞ :=
  ⨅ (F : Set (Sym2 V)) (_ : IsEdgeCut H F), F.encard

/-! ### Step 1 of Stage 1, started from any graph (Theorem 1) -/

/-- A run of **Step 1 of Stage 1** of EC-SBM on a cluster with vertex set `V` and desired edge
connectivity `k`, started from a graph `N₀` on a vertex set `V₀ ⊆ V` (Section "Theoretical
guarantees" and Theorem 1). The vertices of `V` outside `V₀` are added one at a time, in the order
`order 0, order 1, …, order (p - 1)`, and the vertex `order j` is made adjacent to the `k`
vertices of `nbrs j`, which are already present: each lies in `V₀` or was added before
`order j`. The choices of the order and of the neighbours are arbitrary. Each added vertex gets
exactly `k` neighbours, as Section "Theoretical guarantees" says; so there is no run that adds a
vertex while fewer than `k` vertices are present. -/
structure Step1Run (V : Type*) (k : ℕ) where
  /-- The vertex set of the initial graph. -/
  V₀ : Set V
  /-- The initial graph, on the vertex set `V₀`. -/
  N₀ : SimpleGraph V₀
  /-- The number of vertices added to the initial graph. -/
  p : ℕ
  /-- The order in which the vertices outside `V₀` are added: `order j` is added `j`-th. -/
  order : Fin p ≃ (V₀ᶜ : Set V)
  /-- The vertices that `order j` is made adjacent to. -/
  nbrs : Fin p → Finset V
  /-- Each of them is already present when `order j` is added. -/
  nbrs_present : ∀ j, ∀ u ∈ nbrs j, u ∈ V₀ ∨ ∃ i < j, (order i : V) = u
  /-- There are exactly `k` of them. -/
  card_nbrs : ∀ j, (nbrs j).card = k

/-- The graph that a run of Step 1 outputs: the graph on all of `V` whose edges are the edges of
`N₀` and, for each `j`, the edges joining `order j` to the vertices of `nbrs j`. -/
def Step1Run.output {V : Type*} {k : ℕ} (r : Step1Run V k) : SimpleGraph V :=
  r.N₀.map Subtype.val ⊔ fromEdgeSet {e | ∃ j, ∃ u ∈ r.nbrs j, e = s((r.order j : V), u)}

/-! ### The three stages of EC-SBM (Theorem 2) -/

/-- The non-singleton clusters of a clustering `𝒞` of the vertices `W` of a network: the clusters
of the clustered subnetwork. The vertices of the other clusters, which are singletons, are the
outliers (Section "Terminology"). -/
def nonsingletonClusters {W : Type*} [Fintype W] [DecidableEq W]
    (𝒞 : Finpartition (Finset.univ : Finset W)) : Finset (Finset W) :=
  𝒞.parts.filter fun C ↦ 1 < C.card

/-- The desired edge connectivity of a cluster `C` of the empirical network `G`: the minimum cut
size of `C` in `G` (Stage 1). It is finite when `C` has at least two vertices, the only case in
which it is used; for a singleton cluster the minimum cut size is `⊤`, and this is `0`. -/
noncomputable def desiredConnectivity {W : Type*} (G : SimpleGraph W) (C : Finset W) : ℕ :=
  (minCutSize (G.induce (C : Set W))).toNat

/-- Adding the edges of a multigraph `M` to a graph `H`, and then removing the excess edges: every
self-loop, and all but one edge of every set of parallel edges (Steps 2a and 2b of Stage 1, and
Stage 2). The multigraph is the multiset of its edges, an edge `s(v, v)` being a self-loop. -/
def addThenSimplify {W : Type*} (H : SimpleGraph W) (M : Multiset (Sym2 W)) : SimpleGraph W :=
  fromEdgeSet (H.edgeSet ∪ {e | e ∈ M})

/-- A run of **EC-SBM** on the clustered empirical network `(G, 𝒞)` (Sections "The EC-SBM network
simulator" and "A three-stage generation of the synthetic network"). The synthetic network has
the vertices `W` of `G`, and its clustering is `𝒞`. A run consists of:

* Stage 1, Step 1: for each non-singleton cluster `C`, a run of Step 1 on the vertices of `C` with
  the desired edge connectivity of `C`, started from any graph;
* Stage 1, Step 2a: the multigraph that SBM generates with the updated parameters, any multigraph;
* Stage 2: the multigraph that SBM generates for the outlier subnetwork, any multigraph;
* Stage 3: the edges that degree correction adds, any edges.

The model does not restrict what SBM generates or which edges degree correction adds, so it
covers every run of EC-SBM. -/
structure Run {W : Type*} [Fintype W] [DecidableEq W] (G : SimpleGraph W)
    (𝒞 : Finpartition (Finset.univ : Finset W)) where
  /-- Stage 1, Step 1: a run of Step 1 on each non-singleton cluster `C`. -/
  step1 : ∀ C ∈ nonsingletonClusters 𝒞, Step1Run (C : Set W) (desiredConnectivity G C)
  /-- Stage 1, Step 2a: the multigraph that SBM generates. -/
  stage1SBM : Multiset (Sym2 W)
  /-- Stage 2: the multigraph that SBM generates for the outlier subnetwork. -/
  stage2SBM : Multiset (Sym2 W)
  /-- Stage 3: the edges that degree correction adds. -/
  stage3 : SimpleGraph W

namespace Run

variable {W : Type*} [Fintype W] [DecidableEq W] {G : SimpleGraph W}
  {𝒞 : Finpartition (Finset.univ : Finset W)}

/-- The result of Step 1 of Stage 1 (`N₀` in the proof of Theorem 2): the union of the spanning
subnetworks that Step 1 generates for the non-singleton clusters. -/
noncomputable def step1Output (r : Run G 𝒞) : SimpleGraph W :=
  ⨆ (C) (hC : C ∈ nonsingletonClusters 𝒞), (r.step1 C hC).output.map Subtype.val

/-- The result of Stage 1 (`N₁` in the proof of Theorem 2), the synthetic clustered subnetwork:
Step 2a adds the multigraph that SBM generates, and Step 2b removes the excess edges. -/
noncomputable def stage1Output (r : Run G 𝒞) : SimpleGraph W :=
  addThenSimplify r.step1Output r.stage1SBM

/-- The result of Stage 2, the partially complete synthetic network: the synthetic outlier
subnetwork that SBM generates is added, and the excess edges are removed. -/
noncomputable def stage2Output (r : Run G 𝒞) : SimpleGraph W :=
  addThenSimplify r.stage1Output r.stage2SBM

/-- The synthetic network that EC-SBM returns: Stage 3 adds edges to improve the fit to the
degree sequence. -/
noncomputable def output (r : Run G 𝒞) : SimpleGraph W :=
  r.stage2Output ⊔ r.stage3

end Run

end ECSBM
-- END SHARED DEFINITIONS

namespace ECSBM.Challenge

open SimpleGraph

/-- **Theorem 1.** Let `C` be a cluster on vertex set `V`, and let `k` be the desired
edge-connectivity. Let `N₀` be any graph on the vertex set `V₀ ⊆ V` that is `k`-edge-connected.
Then after completing Step 1 of Stage 1 for this cluster, the output synthetic network `G` for `C`
has every node in `V` and is `k`-edge-connected.

The run adds every vertex outside `V₀` (the first conjunct, true by construction), and its output
is a graph on all of `V`. -/
theorem theorem1 {V : Type*} {k : ℕ} (r : Step1Run V k) (hN₀ : r.N₀.IsEdgeConnected k) :
    (∀ v : V, v ∈ r.V₀ ∨ ∃ j, (r.order j : V) = v) ∧ r.output.IsEdgeConnected k := by
  sorry

/-- **Theorem 2.** Let `G` be the clustered empirical network from which we derive parameters for
EC-SBM, and let `𝒞` denote its clustering. For a given cluster `C ∈ 𝒞`, let `N(C)` denote the
corresponding cluster in the synthetic network `N` generated by EC-SBM, allowing for any way of
initializing Step 1 of Stage 1. Then, for all clusters `C`, the size of the minimum edge cut for
`N(C)` in `N` is at least the size of the minimum edge cut for `C` in `G`. -/
theorem theorem2 {W : Type*} [Fintype W] [DecidableEq W] (G : SimpleGraph W)
    (𝒞 : Finpartition (Finset.univ : Finset W)) (r : Run G 𝒞)
    (hinit : ∀ C (hC : C ∈ nonsingletonClusters 𝒞),
      (r.step1 C hC).N₀.IsEdgeConnected (desiredConnectivity G C)) :
    ∀ C ∈ 𝒞.parts,
      minCutSize (G.induce (C : Set W)) ≤ minCutSize (r.output.induce (C : Set W)) := by
  sorry

/-- The minimum cut size of a graph is at least `k` exactly when the graph is `k`-edge-connected
in Mathlib's sense. -/
theorem le_minCutSize_iff {V : Type*} (H : SimpleGraph V) (k : ℕ) :
    (k : ℕ∞) ≤ minCutSize H ↔ H.IsEdgeConnected k := by
  sorry

/-- The minimum cut size of a graph is `0` exactly when the graph is not preconnected, that is,
when it has at least two connected components. -/
theorem minCutSize_eq_zero_iff {V : Type*} (H : SimpleGraph V) :
    minCutSize H = 0 ↔ ¬ H.Preconnected := by
  sorry

/-- The complete graph on `n + 2` vertices has minimum cut size `n + 1`. -/
theorem minCutSize_completeGraph (n : ℕ) :
    minCutSize (completeGraph (Fin (n + 2))) = n + 1 := by
  sorry

/-- EC-SBM can be run on every clustered network, with Step 1 started, in every non-singleton
cluster, from a complete graph on `k + 1` of its vertices, `k` being the desired edge connectivity
of the cluster. These initial graphs are `k`-edge-connected, so the run meets the hypothesis of
Theorem 2. -/
theorem Run.exists_clique {W : Type*} [Fintype W] [DecidableEq W] (G : SimpleGraph W)
    (𝒞 : Finpartition (Finset.univ : Finset W)) :
    ∃ r : Run G 𝒞, ∀ C (hC : C ∈ nonsingletonClusters 𝒞),
      (r.step1 C hC).V₀.ncard = desiredConnectivity G C + 1 ∧ (r.step1 C hC).N₀ = ⊤ ∧
        (r.step1 C hC).N₀.IsEdgeConnected (desiredConnectivity G C) := by
  sorry

end ECSBM.Challenge
