name = "ECSBM"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ECSBM", "Challenge", "Solution"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.35.0-rc4"

[[lean_lib]]
name = "ECSBM"
globs = ["ECSBM.+"]

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
