module

public import ECSBM.CliqueRun
public import ECSBM.Subnetworks

/-!
# The solution: the Challenge's theorems, proved from the library

Each theorem of `Challenge.lean` is restated here word for word, with the same name, and proved
from the library `ECSBM`. The Challenge's copy of the shared definitions is the block of
`ECSBM/Defs.lean`, so the two environments contain the same definitions, and Comparator
(`comparator.json`) checks that each theorem below proves exactly the Challenge's statement.

This module imports the whole library, and serves as its entry point.
-/

@[expose] public section

namespace ECSBM.Challenge

open SimpleGraph

/-- **Theorem 1.** Let `C` be a cluster on vertex set `V`, and let `k` be the desired
edge-connectivity. Let `N₀` be any graph on the vertex set `V₀ ⊆ V` that is `k`-edge-connected.
Then after completing Step 1 of Stage 1 for this cluster, the output synthetic network `G` for `C`
has every node in `V` and is `k`-edge-connected.

The run adds every vertex outside `V₀` (the first conjunct, true by construction), and its output
is a graph on all of `V`. -/
theorem theorem1 {V : Type*} {k : ℕ} (r : Step1Run V k) (hN₀ : r.N₀.IsEdgeConnected k) :
    (∀ v : V, v ∈ r.V₀ ∨ ∃ j, (r.order j : V) = v) ∧ r.output.IsEdgeConnected k :=
  ECSBM.theorem1 r hN₀

/-- **Theorem 2.** Let `G` be the clustered empirical network from which we derive parameters for
EC-SBM, and let `𝒞` denote its clustering. For a given cluster `C ∈ 𝒞`, let `N(C)` denote the
corresponding cluster in the synthetic network `N` generated by EC-SBM, allowing for any way of
initializing Step 1 of Stage 1. Then, for all clusters `C`, the size of the minimum edge cut for
`N(C)` in `N` is at least the size of the minimum edge cut for `C` in `G`. -/
theorem theorem2 {W : Type*} [Fintype W] [DecidableEq W] (G : SimpleGraph W)
    (𝒞 : Finpartition (Finset.univ : Finset W)) (r : Run G 𝒞)
    (hinit : ∀ C (hC : C ∈ nonsingletonClusters 𝒞),
      (r.step1 C hC).N₀.IsEdgeConnected (desiredConnectivity G C)) :
    ∀ C ∈ 𝒞.parts,
      minCutSize (G.induce (C : Set W)) ≤ minCutSize (r.output.induce (C : Set W)) :=
  ECSBM.theorem2 G 𝒞 r hinit

/-- The minimum cut size of a graph is at least `k` exactly when the graph is `k`-edge-connected
in Mathlib's sense. -/
theorem le_minCutSize_iff {V : Type*} (H : SimpleGraph V) (k : ℕ) :
    (k : ℕ∞) ≤ minCutSize H ↔ H.IsEdgeConnected k :=
  ECSBM.le_minCutSize_iff H k

/-- The minimum cut size of a graph is `0` exactly when the graph is not preconnected, that is,
when it has at least two connected components. -/
theorem minCutSize_eq_zero_iff {V : Type*} (H : SimpleGraph V) :
    minCutSize H = 0 ↔ ¬ H.Preconnected :=
  ECSBM.minCutSize_eq_zero_iff H

/-- The complete graph on `n + 2` vertices has minimum cut size `n + 1`. -/
theorem minCutSize_completeGraph (n : ℕ) :
    minCutSize (completeGraph (Fin (n + 2))) = n + 1 :=
  ECSBM.minCutSize_completeGraph n

/-- EC-SBM can be run on every clustered network, with Step 1 started, in every non-singleton
cluster, from a complete graph on `k + 1` of its vertices, `k` being the desired edge connectivity
of the cluster. These initial graphs are `k`-edge-connected, so the run meets the hypothesis of
Theorem 2. -/
theorem Run.exists_clique {W : Type*} [Fintype W] [DecidableEq W] (G : SimpleGraph W)
    (𝒞 : Finpartition (Finset.univ : Finset W)) :
    ∃ r : Run G 𝒞, ∀ C (hC : C ∈ nonsingletonClusters 𝒞),
      (r.step1 C hC).V₀.ncard = desiredConnectivity G C + 1 ∧ (r.step1 C hC).N₀ = ⊤ ∧
        (r.step1 C hC).N₀.IsEdgeConnected (desiredConnectivity G C) :=
  ECSBM.Run.exists_clique G 𝒞

end ECSBM.Challenge
